
var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-138501898-2"]),_gaq.push(["_trackPageview"]),function(){var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="https://ssl.google-analytics.com/ga.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)}();

function setHeights(){document.querySelectorAll(".middle__wrap:not(.middle__img_wr)").forEach(function(e){let t=0;for(var r=0;r<e.children.length;r++)t+=e.children[r].offsetHeight;e.style.height=t+"px"});let e=document.querySelector(".middle__img_wr"),t=e.children[0].children[0].offsetHeight;e.style.height=t+"px"}setHeights(),window.addEventListener("resize",setHeights);let dom_observer=new MutationObserver(setHeights);dom_observer.observe(document.documentElement,{childList:!0,subtree:!0,characterData:!0});

let triggerLink=document.querySelectorAll(".middle__link");triggerLink.forEach(function(e){e.addEventListener("click",function(e){_gaq.push(["_trackEvent","section_clicked",e.target.id]),e.preventDefault(),this.classList.add("clicked"),this.parentNode.classList.toggle("opened"),this.parentNode.parentNode.classList.toggle("condition")})});let imgPopUp=document.querySelector(".popUp__img"),imgClick=document.querySelectorAll(".imgClick");imgClick.forEach(function(e){e.addEventListener("click",function(e){e.preventDefault(),imgPopUp.src=e.target.src;let t=e.target.getAttribute("data-desc");document.querySelector(".popUp__text").innerHTML=t,document.querySelector(".popUp").classList.add("show"),_gaq.push(["_trackEvent","image_clicked",imgPopUp.src])})});let imgClose=document.querySelector(".popUp__close");imgClose.addEventListener("click",function(e){e.preventDefault(),document.querySelector(".popUp").classList.add("hide"),setTimeout(function(){document.querySelector(".popUp").classList.remove("show"),document.querySelector(".popUp").classList.remove("hide")},1e3)});let closeSection=document.querySelectorAll(".middle__close");closeSection.forEach(function(e){e.addEventListener("click",function(e){e.preventDefault(),this.parentNode.classList.toggle("opened"),this.parentNode.parentNode.classList.toggle("condition"),triggerLink.forEach(function(e){e.classList.remove("clicked")}),_gaq.push(["_trackEvent","close_section","close_section"])})});

document.querySelector(".top-interactive_1").addEventListener("click",function(e){e.preventDefault(),this.classList.add("hide"),document.querySelector(".top-interactive_2").classList.add("show"),_gaq.push(["_trackEvent","top_hidden_click","1"])}),document.querySelector(".top-interactive_2").addEventListener("click",function(e){e.preventDefault(),this.classList.add("hide"),document.querySelector(".top__text").classList.add("show"),_gaq.push(["_trackEvent","top_hidden_click","2"])}),document.querySelector(".logo").addEventListener("click",function(e){_gaq.push(["_trackEvent","logo_clicked","logo"])}),document.querySelector(".closeVideo").addEventListener("click",function(){let e=document.querySelector(".middle__video").getAttribute("src");document.querySelector(".middle__video").setAttribute("src",e)});

if(-1!=window.location.href.indexOf("how_to_use")&&(document.querySelector(".middle__item:nth-child(3) .middle__link").classList.add("clicked"),document.querySelector(".middle__item:nth-child(3) .middle__link").parentNode.classList.toggle("opened"),document.querySelector(".middle__item:nth-child(3) .middle__link").parentNode.parentNode.classList.toggle("condition")),-1!=window.location.href.indexOf("greetings")){const e=document.querySelector(".greeting");e.classList.add("greeting-vis"),setTimeout(function(){e.classList.add("greeting-hid")},1e4)}

console.log("%c Hi there!","color: #efbb35"),console.log(" "),console.log("%c What do u want to find?","color: #efbb35"),console.log(" "),console.log("%c There are few hidden possibilities at this website. Can you find them?","color: #efbb35"),console.log(" "),console.log("%c If you have errors within console, disable adblock or hide network errors. Theese are not mine:)","color: #efbb35"),console.log(" "),console.log("%c Have a good day!","color: #efbb35");
